GET http://localhost:5000/users

################################

POST http://localhost:5000/users
Content-Type: application/json

{
    "username" : "lukasz",
    "city" : "wroclaw"
}

################################

PUT http://localhost:5000/users/1
Content-Type: application/json

{
    "username" : "Pawel",
    "city" : "Warszawa"
}

################################

DELETE  http://localhost:5000/users/1
Content-Type: application/json


################################


PATCH  http://localhost:5000/users/4
Content-Type: application/json

{
    "city" : "Wroclaw"
}


################################

DELETE http://localhost:5000/users/all
Content-Type: application/json

